### ISSUE TITLE
TAP

### ISSUE THREAD

**Issue by Guiste9** [Guiste9/GP-almoco-zeRAfila#1]
Objetivo: Desenvolver o Termo de Abertura do Projeto (TAP) para o Sistema de Recarga do Cartão Acadêmico, estabelecendo detalhadamente o escopo, os principais stakeholders, o cronograma e os recursos essenciais ao desenvolvimento do sistema.

Atividades a serem realizadas:

Concluir o preenchimento do TAP com informações detalhadas e relevantes.
Disponibilizar o link do TAP no repositório do projeto para consulta.

Critérios de Aceitação:

O TAP deve estar completo e organizado de forma clara, facilitando a compreensão.
O link para o TAP deve estar acessível no repositório para referência.
O TAP deve ser revisado e aprovado por todos os stakeholders envolvidos.

**Comment by Guiste9** [comment]
link do [TAP](https://docs.google.com/document/d/1Ct7gkWCGu_Kb8vknPYHPuq62Zf9OKaYjMll_QpR17K0/edit?tab=t.0)

**Comment by Nayetdet** [comment]
.

**Comment by DerickBessa** [comment]
.

**Comment by Nayetdet** [comment]
.

**Comment by Guiste9** [comment]
Imagem da EAP:

![Diagrama sem nome drawio(1)(1)](https://github.com/user-attachments/assets/4b65dbfe-594d-464d-af37-0984b9bbaa34)

**Comment by Guiste9** [comment]
Dicionário da EAP:
![EAP-3-1](https://github.com/user-attachments/assets/559308dc-ca33-4d1f-8a71-508e8ca6cb5c)

**Comment by Nayetdet** [comment]
![389651813-559308dc-ca33-4d1f-8a71-508e8ca6cb5c (1)](https://github.com/user-attachments/assets/12b836d3-535f-443a-98f5-93914d997c52)

**Comment by Nayetdet** [comment]
![WhatsApp Image 2024-12-05 at 21 37 43](https://github.com/user-attachments/assets/b3a675c9-bf82-4802-b101-46b044f8fd4a)

**Comment by Nayetdet** [comment]
EAP Refatorado
![Image](https://github.com/user-attachments/assets/d643c7c5-8968-4fe6-98f0-e2db13c3ec68)

**Comment by Nayetdet** [comment]
Dicionário da EAP:
![Image](https://github.com/user-attachments/assets/35fe704d-6c64-453b-95e3-fc5b79211200)

**Comment by Nayetdet** [comment]
Cronograma:
![Image](https://github.com/user-attachments/assets/1ad20cf1-4f32-46b1-8a60-00b5298acf8c)

**Comment by nayetdet** [comment]
Protótipo de baixa fidelidade: https://github.com/Guiste9/GP-almoco-zeRAfila/issues/2
