### ISSUE TITLE
Prototipo de baixa fidelidade

### ISSUE THREAD

**Issue by Guiste9** [Guiste9/GP-almoco-zeRAfila#2]
Objetivo:
Criar protótipos de baixa fidelidade para as principais telas do Sistema de recargas do cartão acadêmico com o intuito de demostrar o userflow.

Conteúdo dos Protótipos:
Para Usuários 
 Tela de Login: tela inicial para que o aluno efetue seu cadastro.
 Tela de esqueceu a senha: projetado para recuperar a senha dos usuários.
 Tela Principal (Dashboard): visualização do saldo do usuário e opções de visualizar o histórico de transações.
 Tela de histórico de transações: feito para visualizar as vezes em que o saldo foi adicionado ou removido
 tela de recarga de saldo: utilizado para que o usuário faca a recarga virtualmente.

Critérios de Aceitação:
 Protótipos finalizados e documentados.
 Fácil entendimento para quem visualiza.

**Comment by Guiste9** [comment]
link do [protótipo](https://www.figma.com/design/YpWPcq1nnidZuTBVqkLnHq/Gestão-de-projetos?node-id=0-1&node-type=canvas&t=SNKa4OZUVRwECksn-0)

**Comment by DerickBessa** [comment]
.

**Comment by Nayetdet** [comment]
.

**Comment by DerickBessa** [comment]
https://www.figma.com/design/YpWPcq1nnidZuTBVqkLnHq/Gest%C3%A3o-de-projetos?node-id=0-1&t=znnHnQDShb4wHk1L-1

**Comment by DerickBessa** [comment]
https://www.figma.com/design/karV1ZeHqPsUZaRT50xzpF/Untitled?node-id=0-1&t=UH03eltnb8ZsNLAl-1

**Comment by nayetdet** [comment]
TAP: https://github.com/Guiste9/GP-almoco-zeRAfila/issues/1
