### ISSUE TITLE
Vídeo gestão de projetos

### ISSUE THREAD

**Issue by Guiste9** [Guiste9/GP-almoco-zeRAfila#3]
Objetivo:
Produzir e compartilhar um vídeo que demonstre a estruturação do trabalho do projeto, evidenciando como as atividades foram distribuídas, os responsáveis definidos e os prazos estabelecidos, utilizando a ferramenta de gestão escolhida.

Atividades a serem executadas:

Gravar um vídeo explicando a organização do projeto na ferramenta de gestão.
Carregar o vídeo em uma plataforma apropriada (como Google Drive ou YouTube).
Inserir o link do vídeo como comentário nesta issue.
Critérios de Aceitação:

Link para o vídeo compartilhado.
Vídeo completo, exibindo todas as etapas da organização do projeto.
Estruturação clara e bem organizada das atividades, conforme os requisitos da atividade.

**Comment by Guiste9** [comment]
link do [vídeo]()

**Comment by DerickBessa** [comment]
LINK DA PASTA COM OS VIDEOS: 
https://drive.google.com/file/d/1q6Wj7MZ6F6WsAvBtRl06N7m9wWk8kLhN/view?usp=drive_link

**Comment by Nayetdet** [comment]
.

**Comment by DerickBessa** [comment]
LINK DO VIDEO GP:

https://drive.google.com/drive/folders/17NrvVEjTeW7ySH7C1-2i-FaM0ujGzf7Y?usp=sharing
