### ISSUE TITLE
Cronograma do projeto

### ISSUE THREAD

**Issue by Guiste9** [Guiste9/GP-almoco-zeRAfila#4]
Descrição

O cronograma é um instrumento fundamental para organizar as atividades do projeto ao longo do tempo, assegurando que os prazos sejam cumpridos e as tarefas sejam coordenadas de forma eficiente. Ele deve contemplar as etapas do projeto, as tarefas correspondentes, os responsáveis por cada uma, além de destacar marcos relevantes e datas de entrega.

**Comment by nayetdet** [comment]
![Image](https://github.com/user-attachments/assets/659bcff3-a918-4a86-9671-dcbceb9d089d)

EAP: https://github.com/Guiste9/GP-almoco-zeRAfila/issues/7
Dicionário da EAP: https://github.com/Guiste9/GP-almoco-zeRAfila/issues/5
Diagrama de redes: https://github.com/Guiste9/GP-almoco-zeRAfila/issues/6

**Comment by nayetdet** [comment]
Arquivo LaTeX do Cronograma do Projeto: https://github.com/Guiste9/GP-almoco-zeRAfila/blob/main/tex/cronograma_eap.tex
