### ISSUE TITLE
Dicionário da EAP

### ISSUE THREAD

**Issue by Guiste9** [Guiste9/GP-almoco-zeRAfila#5]
Descrição

O dicionário da EAP é um documento auxiliar que fornece detalhes sobre cada componente da Estrutura Analítica do Projeto (EAP). Ele especifica os entregáveis, as atividades e os recursos relacionados, facilitando uma compreensão clara e precisa do escopo do projeto.

**Comment by nayetdet** [comment]
![Image](https://github.com/user-attachments/assets/87baa8fb-f267-4aa2-b044-ef71269ec401)
EAP: https://github.com/Guiste9/GP-almoco-zeRAfila/issues/7

**Comment by nayetdet** [comment]
Arquivo LaTeX do Dicionário da EAP:

https://github.com/Guiste9/GP-almoco-zeRAfila/blob/main/tex/dicionario_eap.tex
