### ISSUE TITLE
Diagrama de redes

### ISSUE THREAD

**Issue by Guiste9** [Guiste9/GP-almoco-zeRAfila#6]
Descrição

Elaborar um diagrama de rede para ilustrar as atividades do projeto. O diagrama deve abranger todas as atividades principais, suas interdependências e os tempos estimados de execução, possibilitando a identificação do caminho crítico do projeto.

**Comment by nayetdet** [comment]
Diagrama de redes:
![Image](https://github.com/user-attachments/assets/df990a8d-a6e4-4813-900c-402bdcedd6cb)

EAP: https://github.com/Guiste9/GP-almoco-zeRAfila/issues/7
Cronograma do Projeto: https://github.com/Guiste9/GP-almoco-zeRAfila/issues/4
Dicionário da EAP: https://github.com/Guiste9/GP-almoco-zeRAfila/issues/5

**Comment by nayetdet** [comment]
Link do [site usado para gerar esse diagrama](https://dreampuf.github.io/GraphvizOnline/?engine=dot#digraph%20Projeto%20%7B%0A%20%20%20%20rankdir%3DLR%3B%0A%20%20%20%20node%20%5Bshape%3Dbox%2C%20style%3Dfilled%2C%20color%3Dlightblue%5D%3B%0A%0A%20%20%20%20start%20%5Bshape%3Dcircle%2C%20label%3D%22In%C3%ADcio%20do%20Projeto%22%2C%20style%3Dfilled%2C%20color%3Dlightgreen%2C%20width%3D0.5%2C%20height%3D0.5%5D%3B%0A%20%20%20%20end%20%5Bshape%3Dcircle%2C%20label%3D%22Final%20do%20Projeto%22%2C%20style%3Dfilled%2C%20color%3Dlightcoral%2C%20width%3D0.5%2C%20height%3D0.5%5D%3B%0A%0A%20%20%20%20subgraph%20cluster_planejamento%20%7B%0A%20%20%20%20%20%20%20%20label%3D%22Planejamento%22%3B%0A%20%20%20%20%20%20%20%20%221.1.1%22%20%5Blabel%3D%221.1.1%5CnTempo%3A%204%20semanas%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.1.2%22%20%5Blabel%3D%221.1.2%5CnTempo%3A%203%20semanas%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.1.3%22%20%5Blabel%3D%221.1.3%5CnTempo%3A%203%20semanas%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.1.4%22%20%5Blabel%3D%221.1.4%5CnTempo%3A%203%20semanas%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.1.5%22%20%5Blabel%3D%221.1.5%5CnTempo%3A%203%20semanas%22%5D%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20subgraph%20cluster_desenvolvimento%20%7B%0A%20%20%20%20%20%20%20%20label%3D%22Desenvolvimento%22%3B%0A%20%20%20%20%20%20%20%20%221.2.1%22%20%5Blabel%3D%221.2.1%5CnTempo%3A%206%20semanas%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.2.2%22%20%5Blabel%3D%221.2.2%5CnTempo%3A%204%20semanas%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.2.3%22%20%5Blabel%3D%221.2.3%5CnTempo%3A%204%20semanas%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.2.4%22%20%5Blabel%3D%221.2.4%5CnTempo%3A%203%20semanas%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.2.5%22%20%5Blabel%3D%221.2.5%5CnTempo%3A%204%20semanas%22%5D%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20subgraph%20cluster_testes%20%7B%0A%20%20%20%20%20%20%20%20label%3D%22Testes%22%3B%0A%20%20%20%20%20%20%20%20%221.3.1%22%20%5Blabel%3D%221.3.1%5CnTempo%3A%202%20semanas%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.3.2%22%20%5Blabel%3D%221.3.2%5CnTempo%3A%202%20semanas%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.3.3%22%20%5Blabel%3D%221.3.3%5CnTempo%3A%204%20semanas%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.3.4%22%20%5Blabel%3D%221.3.4%5CnTempo%3A%202%20semanas%22%5D%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20subgraph%20cluster_implantacao%20%7B%0A%20%20%20%20%20%20%20%20label%3D%22Implanta%C3%A7%C3%A3o%22%3B%0A%20%20%20%20%20%20%20%20%221.4.1%22%20%5Blabel%3D%221.4.1%5CnTempo%3A%202%20semanas%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.4.2%22%20%5Blabel%3D%221.4.2%5CnTempo%3A%202%20semanas%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.4.3%22%20%5Blabel%3D%221.4.3%5CnTempo%3A%201%20semana%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.4.4%22%20%5Blabel%3D%221.4.4%5CnTempo%3A%201%20semana%22%5D%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20subgraph%20cluster_treinamento%20%7B%0A%20%20%20%20%20%20%20%20label%3D%22Treinamento%20e%20Suporte%22%3B%0A%20%20%20%20%20%20%20%20%221.5.1%22%20%5Blabel%3D%221.5.1%5CnTempo%3A%206%20semanas%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.5.2%22%20%5Blabel%3D%221.5.2%5CnTempo%3A%202%20semanas%22%5D%3B%0A%20%20%20%20%20%20%20%20%221.5.3%22%20%5Blabel%3D%221.5.3%5CnTempo%3A%202%20semanas%22%5D%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20start%20-%3E%20%221.1.1%22%3B%0A%20%20%20%20%221.5.2%22%20-%3E%20end%3B%0A%20%20%20%20%221.5.3%22%20-%3E%20end%3B%0A%0A%20%20%20%20%2F%2F%20Planejamento%0A%20%20%20%20%221.1.1%22%20-%3E%20%221.1.2%22%3B%0A%20%20%20%20%221.1.1%22%20-%3E%20%221.1.3%22%3B%0A%20%20%20%20%221.1.2%22%20-%3E%20%221.1.4%22%3B%0A%20%20%20%20%221.1.3%22%20-%3E%20%221.1.4%22%3B%0A%20%20%20%20%221.1.4%22%20-%3E%20%221.1.5%22%3B%0A%0A%20%20%20%20%2F%2F%20Desenvolvimento%0A%20%20%20%20%221.1.5%22%20-%3E%20%221.2.1%22%3B%0A%20%20%20%20%221.2.1%22%20-%3E%20%221.2.2%22%3B%0A%20%20%20%20%221.2.1%22%20-%3E%20%221.2.3%22%3B%0A%20%20%20%20%221.2.2%22%20-%3E%20%221.2.4%22%3B%0A%20%20%20%20%221.2.3%22%20-%3E%20%221.2.4%22%3B%0A%20%20%20%20%221.2.4%22%20-%3E%20%221.2.5%22%3B%0A%0A%20%20%20%20%2F%2F%20Testes%0A%20%20%20%20%221.2.5%22%20-%3E%20%221.3.1%22%3B%0A%20%20%20%20%221.3.1%22%20-%3E%20%221.3.2%22%3B%0A%20%20%20%20%221.3.1%22%20-%3E%20%221.3.3%22%3B%0A%20%20%20%20%221.3.2%22%20-%3E%20%221.3.4%22%3B%0A%20%20%20%20%221.3.3%22%20-%3E%20%221.3.4%22%3B%0A%0A%20%20%20%20%2F%2F%20Implanta%C3%A7%C3%A3o%0A%20%20%20%20%221.3.4%22%20-%3E%20%221.4.1%22%3B%0A%20%20%20%20%221.4.1%22%20-%3E%20%221.4.2%22%3B%0A%20%20%20%20%221.4.2%22%20-%3E%20%221.4.3%22%3B%0A%20%20%20%20%221.4.3%22%20-%3E%20%221.4.4%22%3B%0A%0A%20%20%20%20%2F%2F%20Treinamento%0A%20%20%20%20%221.4.4%22%20-%3E%20%221.5.1%22%3B%0A%20%20%20%20%221.5.1%22%20-%3E%20%221.5.2%22%3B%0A%20%20%20%20%221.5.1%22%20-%3E%20%221.5.3%22%3B%0A%7D)

**Comment by nayetdet** [comment]
Código fonte do diagrama: https://github.com/Guiste9/GP-almoco-zeRAfila/blob/main/graphviz/diagrama_redes.dot

Caso não consiga acessar o link acima, você pode entrar [neste site](https://dreampuf.github.io/GraphvizOnline) e colar o código fonte, para visualizar o diagrama diretamente.
