### ISSUE TITLE
EAP

### ISSUE THREAD

**Issue by Guiste9** [Guiste9/GP-almoco-zeRAfila#7]
A EAP é uma ferramenta de gerenciamento de projetos que organiza e define o escopo do projeto de forma hierárquica. Ela divide o projeto em entregas menores e mais gerenciáveis, chamadas de pacotes de trabalho, facilitando o planejamento, a execução, o monitoramento e o controle.

**Comment by nayetdet** [comment]
![Image](https://github.com/user-attachments/assets/b9286233-1d81-40ac-a8be-348b65130025)

**Comment by nayetdet** [comment]
TAP: https://github.com/Guiste9/GP-almoco-zeRAfila/issues/1
